/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "xewucyndxkjnkhdonpwl"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhld3VjeW5keGtqbmtoZG9ucHdsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA5Mzc0NzksImV4cCI6MjA4NjUxMzQ3OX0.pj4AIAgZPSAbUKVt-G-ec2jZayUCsYYorhcTOuWcIRo"